<section class="flex flex-col w-full items-center">
    <h1 class="mt-4 text-xl lg:text-2xl">Prava i obaveze potrošača</h1>
    <p class="mt-12 w-5/6 lg:w-2/3 text-center">Poslednje izmene na ovoj stranici bile su 18.4.2018.</p>
    <div class="mt-12 w-full lg:w-4/5">
        <br><p>Prodavac je dužan potrošača (kupca) upoznati o osnovnim obeležjima robe (proizvoda) koju kupuje, o ceni, načinu plaćanja, načinu i roku isporuke i načinu izvršenja drugih ugovornih obaveza, o funkcionalnosti robe, ukljucujuci i mere zaštite kupljene robe, o relevantnoj interoperabilnosti kupljene robe o kojima trgovac ima saznanja, o postojanju i uslovima postprodajnih usluga i garancijama, o postojanju zakonske odgovornosti Prodavca zbog nesaobraznosti robe ugovoru, o načinu izjavljivanja reklamacije, a naročito o mestu prijema i načinu postupanja po njima, kao i uslovima koji se odnose na ostvarivanje prava potrošača po osnovu saobraznosti, o dostupnosti servisa, odnosno održavanja i opravke za vreme i posle prestanka perioda u kojem Prodavac odgovara za nesaobraznost robe ugovoru, odnosno posle prestanka proizvodnje i uvoza robe.</p>
        <br><p>Prodavac će Potrošaču predati uputstvo za upotrebu i montažu. Ako isporučena roba nije saobrazna ugovoru, Potrošač nakon što obavesti Prodavca o nesaobraznosti, ima pravo da zahteva od Prodavca da otkloni nesaobraznost, bez naknade, opravkom ili zamenom, odnosno da zahteva odgovarajuće umanjenje cene ili da raskine ugovor u pogledu te robe.</p>
        <br><p>Potrošač ima pravo da bira da nesaobraznost robe trgovac otkloni opravkom ili zamenom.</p>
        <br><p>Ako otklanjanje nesaobraznosti u skladu sa stavom 2. ovog clana nije moguće, Potrošač ima pravo da zahteva odgovarajuće umanjenje cene ili raskid ugovora ako:</p>
        <br><p>• Nesaobraznost ne može da se otkloni opravkom ili zamenom uopšte niti u primerenom roku<br />• Ne može da ostvari pravo na opravku ili zamenu, odnosno ako Prodavac nije izvršio opravku ili zamenu u primerenom roku<br />• Opravka ili zamena ne može da se sprovede bez značajnijih nepogodnosti za potrošača zbog prirode robe i njene namene<br />• Otklanjanje nesaobraznosti opravkom ili zamenom predstavlja nesrazmerno opterećenje za Prodavca<br />• Nesrazmerno opterećenje za Prodavca u smislu stava 3. tacka 4) ovog clana, javlja se ako u poreenju sa umanjenjem cene i raskidom ugovora, stvara preterane troškove, uzimajući u obzir:<br />1. Vrednost robe koju bi imala da je saobrazna ugovoru<br />2. Značaj saobraznosti u konkretnom slučaju<br />3. Da li se saobraznost može otkloniti bez značajnijih nepogodnosti za potrošača</p>
        <br><p>Potrošač ima pravo da zahteva zamenu, odgovarajuće umanjenje cene ili da raskine ugovor zbog istog ili drugog nedostatka saobraznosti koji se posle prve opravke pojavi, a ponovna opravka je moguća samo uz izričitu saglasnost potrošača. uzimajući u obzir prirodu robe i svrhu zbog koje je Potrošač nabavio, opravka ili zamena robe mora se izvršiti u primerenom roku bez Značajnih neugodnosti za potrošača i uz njegovu saglasnost. Ako se nesaobraznost pojavi u roku od šest meseci od dana prelaska rizika na potrošača, on ima pravo da bira između zahteva da se nesaobraznost otkloni zamenom, odgovarajućim umanjenjem cene ili da izjavi da raskida ugovor, a otklanjanje nesaobraznosti moguće je opravkom uz izričitu saglasnost potrošača. Potrošač ne može da raskine ugovor ako je nesaobraznost robe neznatna. Potrošač neće zloupotrebljavati svoja prava po osnovu nesaobraznosti, u protivnom, biće dužan da Prodavcu naknadu svaku štetu koju mu je time prouzrokovao. Prodavac će utvrditi da li postoji nesaobraznost robe koju je Potrošač istakao i ako utvrdi da je Potrošač i pored nepostojanja nesaobraznosti ili postojanja neznatne nesaobraznosti raskinuo ugovor, od potrošača će tražiti naknadu štete zbog neosnovanog raskida ugovora. Pod štetom se podrazumeva kako stvarna šteta tako i izmakla korist.</p>
        <br><p>Prodavac je odgovoran za nesaobraznost robe ugovoru koja se pojavi u roku od dve godine od dana prelaska rizika na potrošača. Ako nesaobraznost nastane u roku od šest meseci od dana prelaska rizika na potrošača, pretpostavlja se da je nesaobraznost postojala u trenutku prelaska rizika, osim ako je to u suprotnosti sa prirodom robe i prirodom određene nesaobraznosti. Kod prodaje polovne robe, Prodavac odgovara za nesaobraznost robe u roku od jedne godine.</p>
        <br><p>Prodavac se obavezuje da će isporučiti robu sa kompletnom dokumentacijom i pripadajucom ambalažom tj. kompletnu kakva je dobavljena od proizvođača, uvoznika ili distributera.</p>
        <br><p>Da bi Potrošač ostvarilo pravo na saobraznost dužan je, pri predaji robe Prodavcu na servis, uz neispravan artikal priložiti dokumentaciju koja dolazi uz proizvod, (po mogućstvu neoštećenu ambalažu), original ili kopiju Ugovora o prodaji i fiskalni račun (ili slip) kojim se potvrđuje kupovina robe od Prodavca. Uz to je potrebno navesti detaljan opis kvara kako bi se olakšala provera neispravnosti od strane ovlašćenog lica Prodavca ili ovlašćenih servisera proizvođača. Opis kvara, serijski broj, naziv artikla, proizvođač artikla, oznaka modela itd. unose se u za to predviđen obrazac (revers). Prodavac se obavezuje da Potrošaču obezbedi ovaj obrazac i popuni isti prilikom prijema robe na servis. Jedan primerak reversa zadržava Prodavac, a drugi Potrošač prilikom predaje proizvoda na servis. Potrošač je dužan da prilikom preuzmanja proizvoda sa reklamacije donese i preda revers odgovornom licu Prodavca u maloprodajnom objektu. U suprotnom, Potrošač neće moci da preuzme robu sa servisa. Zamena delova pre provere dokumentacije nije moguća, kao ni pre provere navedenih nedostataka, osim ukoliko u ćenovniku ili posebnom sertifikatu koji se dobije nije drugacije naznačeno (npr. ukoliko je za odreeni artikl naznačeno da se u slučaju reklamacije menja 1 za 1 u roku odgovornosti za nesaobraznost). Roba koja se šalje na servis poštom ili paketnom distribucijom mora biti propisno zapakovana u kartonsku ambalažu. Svi proizvodi koji su na ovaj način Prodavcu dostavljeni, a koji nisu propisno zapakovani ili oni kod kojih je došlo do vidljivih mehaničkih oštećenja samog proizvoda u toku transporta neće biti preuzeti od strane Prodavca, već će biti vraćeni pošiljaocu o njegovom trošku. Prodavac ne preuzima nikakvu odgovornost za sva eventualna oštećenja proizvoda i ambalaže koja nastanu u toku transporta na ili sa adrese potrošača. Ukoliko je utvrdjeno fizičko i mehaničko oštećenje robe za koju Prodavca ne odgovara, Prodavac u slučaju povraćaja novca, nije dužan da vrati pun iznos kupoprodajne cene, već će ćenu umanjiti za procenat ili iznos koji odgovara procenjenom procentu ili iznosu umanjenja vrednosti robe usled oštećenja. Procenu će vršiti ovlašćena lica Prodavca (serviseri).</p>
        <br><p>Saobraznost ne pokriva nedostatke, oštećenja i kvarove nastale nepravilnim i nestrucnim rukovanjem proizvodom. U nepravilno rukovanje su ukljućeni i propusti poput spajanja uređaja na izvore energije koji nisu propisani uputstvom za rukovanjem kao i korišćenje uređaja u nepredviđenim uslovima i prostorima. Pravo na saobraznost Potrošač gubi i u slučaju neovlašćenog popravljanja proizvoda kao i popravljanjem od strane trećeg lica koje nije ovlašćeno od strane Prodavca ili proizvođača.</p>
        <br><p>Prodavac ne preuzima nikakvu odgovornost za podatke na računaru, hard disku ili bilo kom drugom ureaju koji služi za smeštanje podataka.</p>
        <br><p>Prodavac ne vrši instalaciju i montažu robe na adresi potrošača i samim tim ne snosi nikakvu odgovornost za nesaobraznost robe koja je nastala zbog nepravilne instalacije ili montaže, osim ako je do pomenutie nesobraznosti došlo krivicom Prodavca.</p>
        <br><p>U slučaju da kontrolni servis Prodavca utvrdi da je proizvod koji je poslat na popravku po reklamaciji ispravan, biće naplaćen pregled proizvoda po važećem ćenovniku servisa i biće naplaćeni svitransportni troškovi koje je snosio Prodavac. Proizvod će se isporučiti na adresu potrošača tek nakon što Potrošač uplati na naš tekuci račun sve nastale troškove.</p>
        <br><p>U slučaju da se radi o kompletnom računaru kupljenom kod Prodavca, on se obavezuje da utvrdi i otkloni sve nepravilnosti u radu računara. U slučaju kupovine samo određenih komponenata za sastavljanje računara kod Prodavca, kao i u slučaju kada računar nije sastavilo ovlašćeno liće, kod Prodavca, on je dužan samo da proveri ispravnost komponenata kupljenih kod Prodavca. Kompatibilnost komponenata nije predmet saobraznosti ukoliko sve komponente u računaru nisu kupljene kod Prodavca. U slučaju da su sve komponente u računaru kupljene kod Prodavca a dolazi do određenih nekompatibilnosti u međusobnom radu, Prodavac se obavezuje da će u dogovoru sa Potrošačem pronaći rešenje za nastalu situaciju a svakako u korist potrošača.</p>
        <br><p>Potrošač može da izjavi reklamaciju radi ostvarivanja svojih prava iz usled nesaobraznosti robe ugovoru i prava po osnovu garancije, kao i zbog pogrešno obračunate cene i drugih nedostataka, na način koji su opisane u obaveštenju o načinu i mestu primanja reklamacije.</p>
        <br><p>Prodavac je dužan da bez odlaganja, a najkasnije u roku od osam dana od dana prijema reklamacije, pisanim ili elektronskim putem odgovori Potrošaču na izjavljenu reklamaciju. Odgovor Prodavca na reklamaciju mora da sadrži odluku da li prihvata reklamaciju, izjašnjenje o zahtevu potrošača i konkretan predlog i rok za rešavanje reklamacije. Rok ne može da bude duži od 30 dana, od dana podnošenja reklamacije.</p>
        <br><p>Prodavac je dužan da postupi u skladu sa odlukom, predlogom i rokom za rešavanje reklamacije, ukoliko je dobio prethodnu saglasnost potrošača. S toga će potrošača svoju saglasnost dati u najkraćem mogućem roku od momenta prijema odgovora Prodavca na reklamaciju, kako bi Prodavac mogao da reši reklamaciju u gore spomenutom zakonskom roku. Neblagovremeno davanje saglasnoti potrošača smatraće se jednim od objektivnimh razloga zbog kojih Prodavac nije u mogucnosti da udovolji zahtevu potrošača u zakonskom roku.</p>
        <br><p>Ukoliko prodavac iz objektivnih razloga nije u mogucnosti da udovolji zahtevu potrošača u roku koji je dogovoren, dužan je da o produžavanju roka za rešavanje reklamacije obavesti potrošača i navede rok u kome će je rešiti, kao i da dobije njegovu saglasnost, koju će Potrošač dati u najkraćem mogućem roku. Produžavanje roka za rešavanje reklamacija moguće je samo jednom.</p>
        <br><p>Prodavac se obavezuje da će svaki proizvod koji je predat na servis a cija reklamacija nije rešena u dogovorenom roku zameniti novim, istim ili odgovarajućim artiklom. Ukoliko Potrošač ne prihvati zamenu artikla za drugi odgovarajući, Potrošaču će biti vraćen iznos kupoprodajne cene.</p>
        <br><p>Potrošač je dužan da popravljeni proizvod preuzme najkasnije u roku od 30 dana od trenutka kada je dobio obaveštenje da može preuzeti proizvod sa servisa. Nakon isteka tog perioda Prodavac ne preuzima više nikakvu odgovornost za dati proizvod i proizvod može biti predat na recikliranje.</p>
        <br><p>Saobraznost se daje isključivo na ispravnost uređaja a ne na njegovu funkcionalnost jer se podrazumeva da je Potrošač upoznat sa tehničkim karakteristikama proizvoda, pa se saobraznost odnosi na činjenicu da će izabrani proizvod zadovoljiti zahteve potrošača u okviru deklarisanih tehnickih mogucnosti propisanih od strane proizvođača. Saobraznost se ne odnosi na poslove održavanja proizvoda tj. cišćenje i sl. Od potrošača se oćekuje da kupljeni proizvod ne izlaže štetnim dejstvima (duvanski dim, ekstremno prašnjave prostorije, ekstremno hladne ili ekstremno tople prostorije i sl.). Sve eventualne nepravilnosti prouzrokovane ovakvim tretmanom robe će se otklanjati isključivo na teret potrošača po važećem ćenovniku servisnih usluga.</p>
        <br><p>Pravo na saobraznost nije moguće ostvariti ukoliko je do oštećenja ili kvara robe došlo usled transporta nakon isporuke, usled nepravilne montaže, usled nepravilnog održavanja, usled neispravnih elektricnih instalacija, nestabilnog napona ili usled strujnog udara ili udara groma, usled više sile (poplava, zemljotres, požar i sl.), usled nepravilnog korišćenja, usled nepridržavanja proizvođačkog uputstva i preporuka o upotrebi proizvoda, usled korišćenja neodgovarajućeg potrošnog materijala koji nije kupljen uz proizvod, usled bilo kakvog mehaničkog oštećenja proizvoda koje je nastalo krivicom potrošača ili trećeg lica za koje Prodavac ne odgovara, usled neovlašćenog popravljanja proizvoda od strane trećeg lica koje nije ovlašćeno od Prodavca ili proizvođača, ukoliko je proizvod vraćen bez fiskalnog računa ili drugog dokaza da je kupljen kod Prodavca. Potrošač je dužan da prilikom preuzimanja kupljenog proizvoda ustanovi kompletnost i fizicku neoštećenost proizvoda koje preuzima. Naknadne reklamacije koje se odnose na kompletnost i fizičku neoštećenost neće biti prihvaćene.</p>
        <br><p>Potrošač će sačuvati originalnu ambalažu kupljenog prizvoda i koristiti je pri svakom internom i eksternom transportu.</p>
        <br><p>Pre nego što se obrati za tehničku pomoć, Potrošač će proveriti da li su obezbeđeni svi neophodni uslovi za nesmetan rad kupljenog proizvoda.</p>
        <br><p>Softver koji je isporučen uz računar ili uredjaj ne potpada pod uslove saobraznosti.</p>
        <br><p><strong>Detalji ugovora o prodaji na daljinu</strong><br />Član 2.</p>
        <br><p>Kupac potpisivanjem ovog Ugovora potvrđuje da je od strane Prodavca upoznat o osnovnim obeležjima robe (proizvoda) koju kupuje, o ceni, načinu plaćanja, načinu i roku isporuke i načinu izvršenja drugih ugovornih obaveza, o funkcionalnosti robe, uključujući i mere tehničke zaštite digitalnog sadržaja, o relevantnoj interoperabilnosti digitalnog sadržaja sa hardverom i softverom o kojima trgovac ima saznanja, o postojanju i uslovima postprodajnih usluga i garancijama, o postojanju zakonske odgovornosti Prodavca zbog nesaobraznosti robe ugovoru, o načinu izjavljivanja reklamacije, a naročito o mestu prijema i načinu postupanja po njima, kao i uslovima koji se odnose na ostvarivanje prava potrošača po osnovu saobraznosti, o dostupnosti rezervnih delova, priključnih aparata i sličnih delova, tehničkog servisa, odnosno održavanja i opravke za vreme i posle prestanka perioda u kojem Prodavac odgovara za nesaobraznost robe ugovoru, odnosno posle prestanka proizvodnje i uvoza robe. Prodavac je Kupcu predao uputstvo za upotrebu i montažu.</p>
        <br><p>Član 3.</p>
        <br><p>Ako isporučena roba nije saobrazna ugovoru, Kupac nakon što obavesti Prodavca o nesaobraznosti, ima pravo da zahteva od Prodavca da otkloni nesaobraznost, bez naknade, opravkom ili zamenom, odnosno da zahteva odgovarajuće umanjenje cene ili da raskine ugovor u pogledu te robe.</p>
        <br><p>Kupac ima pravo da bira da nesaobraznost robe trgovac otkloni opravkom ili zamenom.</p>
        <br><p>Ako otklanjanje nesaobraznosti u skladu sa stavom 2. ovog člana nije moguće, Kupac ima pravo da zahteva odgovarajuće umanjenje cene ili raskid ugovora ako:</p>
        <br><p>Nesaobraznost ne može da se otkloni opravkom ili zamenom uopšte niti u primerenom roku<br />Ne može da ostvari pravo na opravku ili zamenu, odnosno ako Prodavac nije izvršio opravku ili zamenu u primerenom roku<br />Opravka ili zamena ne može da se sprovede bez značajnijih nepogodnosti za Kupca zbog prirode robe i njene namene<br />Otklanjanje nesaobraznosti opravkom ili zamenom predstavlja nesrazmerno opterećenje za Prodavca.<br />Nesrazmerno opterećenje za Prodavca u smislu stava 3. tačka 4. ovog člana, javlja se ako u poređenju sa umanjenjem cene i raskidom ugovora, stvara preterane troškove, uzimajući u obzir:</p>
        <br><p>Vrednost robe koju bi imala da je saobrazna ugovoru<br />Značaj saobraznosti u konkretnom slučaju<br />Da li se saobraznost može otkloniti bez značajnijih nepogodnosti za Kupca<br />Kupac ima pravo da zahteva zamenu, odgovarajuće umanjenje cene ili da raskine ugovor zbog istog ili drugog nedostatka saobraznosti koji se posle prve opravke pojavi, a ponovna opravka je moguća samo uz izričitu saglasnost Kupca.</p>
        <br><p>Uzimajući u obzir prirodu robe i svrhu zbog koje je Kupac nabavio, opravka ili zamena robe mora se izvršiti u primerenom roku bez značajnih neugodnosti za Kupca i uz njegovu saglasnost.</p>
        <br><p>Ako se nesaobraznost pojavi u roku od šest meseci od dana prelaska rizika na Kupca, on ima pravo da bira između zahteva da se nesaobraznost otkloni zamenom, odgovarajućim umanjenjem cene ili da izjavi da raskida ugovor, a otklanjanje nesaobraznosti moguće je opravkom uz izričitu saglasnost Kupca.</p>
        <br><p>Kupac ne može da raskine ugovor ako je nesaobraznost robe neznatna. Kupac neće zloupotrebljavati svoja prava po osnovu nesaobraznosti, u protivnom, biće dužan da Prodavcu naknadu svaku štetu koju mu je time prouzrokovao. Prodavac će utvrditi da li postoji nesaobraznost robe koju je Kupac istakao i ako utvrdi da je Kupac i pored nepostojanja neosaobraznosti ili postojanja neznatne nesaobraznosti raskinuo ugovor, od Kupca će tražiti naknadu štete zbog neosnovanog raskida ugovora. Pod štetom se podrazumeva kako stvarna šteta tako i izmakla korist.</p>
        <br><p>Prodavac je odgovoran za nesaobraznost robe ugovoru koja se pojavi u roku od dve godine od dana prelaska rizika na Kupca.</p>
        <br><p>Ako nesaobraznost nastane u roku od šest meseci od dana prelaska rizika na Kupca, pretpostavlja se da je nesaobraznost postojala u trenutku prelaska rizika, osim ako je to u suprotnosti sa prirodom robe i prirodom određene nesaobraznosti.</p>
        <br><p>Kod prodaje polovne robe, Prodavac odgovara za nesaobraznost robe u roku od jedne godine.</p>
        <br><p>Član 4.</p>
        <br><p>Prodavac se obavezuje da će isporučiti robu sa kompletnom dokumentacijom i pripadajućom ambalažom tj. kompletnu kakva je dobavljena od proizvođača, uvoznika ili distributera.</p>
        <br><p>Da bi se ostvarilo pravo na saobraznost neophodno je, pri predaji robe Prodavcu na servis, uz neispravan artikal priložiti dokumentaciju koja dolazi uz proizvod, (po mogućstvu neoštećenu ambalažu), original ili kopiju Ugovora o prodaji i fiskalni račun (ili slip) kojim se potvrđuje kupovina robe od Prodavca. Uz to je potrebno navesti detaljan opis kvara kako bi se olakšala provera neispravnosti od strane ovlašćenog lica Prodavca ili ovlašćenih servisera proizvođača. Opis kvara, serijski broj, naziv artikla, proizvođač artikla, oznaka modela itd. unose se u za to predviđen obrazac (revers). Prodavac se obavezuje da Kupcu obezbedi ovaj obrazac i popuni isti prilikom prijema robe na servis. Jedan primerak reversa zadržava Prodavac, a drugi Kupac prilikom predaje proizvoda na servis. Kupac je dužan da prilikom preuzmanja proizvoda sa reklamacije donese i preda revers odgovornom licu Prodavca u maloprodajnom objektu. U suprotnom, Kupac neće moći da preuzme robu sa servisa. Zamena delova pre provere dokumentacije nije moguća, kao ni pre provere navedenih nedostataka, osim ukoliko u ćenovniku ili posebnom sertifikatu koji se dobije nije drugačije naznačeno (npr. ukoliko je za određeni artikl naznačeno da se u slučaju reklamacije menja 1 za 1 u roku odgovornosti za nesaobraznost).</p>
        <br><p>Roba koja se šalje na servis poštom ili paketnom distribucijom mora biti propisno zapakovana u kartonsku ambalažu. Svi proizvodi koji su na ovaj način Prodavcu dostavljeni, a koji nisu propisno zapakovani ili oni kod kojih je došlo do vidljivih mehaničkih oštećenja samog proizvoda u toku transporta neće biti preuzeti od strane Prodavca, već će biti vraćeni pošiljaocu o njegovom trošku. Prodavac ne preuzima nikakvu odgovornost za sva eventualna oštećenja proizvoda i ambaže koja nastanu u toku transporta na ili sa adrese Kupca.</p>
        <br><p>Ukoliko je utvrdjeno fizičko i mehaničko oštećenje robe za koju Prodavca ne odgovara, Prodavac u slučaju povraćaja novca, nije dužan da vrati pun iznos kupoprodajne cene, već će mu umanjiti za procenat ili iznos koji odgovara procenjenom procentu ili iznosu umanjenja vrednosti robe usled oštećenja. Procenu će vršiti ovlašćena lica Prodavca (serviseri).</p>
        <br><p>Saobraznost ne pokriva nedostatke, oštećenja i kvarove nastale nepravilnim i nestručnim rukovanjem proizvodom. U nepravilno rukovanje su uključeni i propusti poput spajanja uređaja na izvore energije koji nisu propisani uputstvom za rukovanjem kao i korišćenje uređaja u nepredviđenim uslovima i prostorima. Pravo na saobraznost kupac gubi i u slučaju neovlašćenog popravljanja proizvoda kao i popravljanjem od strane trećeg lica koje nije ovlašćeno od strane Prodavca ili proizvođača.</p>
        <br><p>Prodavac ne preuzima nikakvu odgovornost za podatke na računaru, hard disku ili bilo kom drugom uređaju koji služi za smeštanje podataka.</p>
        <br><p>Prodavac ne vrši instalaciju i montažu robe na adresi kupca i samim tim ne snosi nikakvu odgovornost za nesaobraznost robe koja je nastala zbog nepravilne instalacije ili montaže, osim ako je do pomenute nesobraznosti došlo krivicom Prodavca.</p>
        <br><p>U slučaju da kontrolni servis Prodavca utvrdi da je proizvod koji je poslat na popravku po reklamaciji ispravan, biće naplaćen pregled proizvoda po važećem ćenovniku servisa i biće naplaćeni svi transportni troškovi koje je snosio Prodavac. Proizvod će se isporučiti na adresu Kupca tek nakon što Kupac uplati na naš tekući račun sve nastale troškove.</p>
        <br><p>U slučaju da se radi o kompletnom računaru kupljenom kod Prodavca, on se obavezuje da utvrdi i otkloni sve nepravilnosti u radu računara.</p>
        <br><p>U slučaju kupovine samo određenih komponenata za sastavljanje računara kod Prodavca, kao i u slučaju kada računar nije sastavilo ovlašćeno liće, kod Prodavca, on je dužan samo da proveri ispravnost komponenata kupljenih kod Prodavca. Kompatibilnost komponenata nije predmet saobraznosti ukoliko sve komponente u računaru nisu kupljene kod Prodavca. U slučaju da su sve komponente u računaru kupljene kod Prodavca a dolazi do određenih nekompatibilnosti u međusobnom radu, Prodavac se obavezuje da će u dogovoru sa Kupćem pronaći rešenje za nastalu situaciju a svakako u korist Kupca.</p>
        <br><p>Član 5.</p>
        <br><p>Kupac može da izjavi reklamaciju radi ostvarivanja svojih prava iz usled nesaobraznosti robe ugovoru i prava po osnovu garancije, kao i zbog pogrešno obračunate cene i drugih nedostataka, na sledeće načine:</p>
        <br><p>Usmeno na adresi Prodavca, telefonom, pisanim putem ili elektronskim putem, na elektronsku (email) adresu Prodavca.<br />
        odnosno na trajnom nosaču zapisa, uz dostavu računa na uvid ili drugog dokaza o kupovini (kopija računa, slip i sl.).<br />
        Prodavac je dužan da bez odlaganja, a najkasnije u roku od osam dana od dana prijema reklamacije, pisanim ili elektronskim putem odgovori Kupcu na izjavljenu reklamaciju. Odgovor Prodavca na reklamaciju mora da sadrži odluku da li prihvata reklamaciju, izjašnjenje o zahtevu Kupca i konkretan predlog i rok za rešavanje reklamacije. Rok ne može da bude duži od 30 dana, od dana podnošenja reklamacije.</p>
        <br><p>Prodavac je dužan da postupi u skladu sa odlukom, predlogom i rokom za rešavanje reklamacije, ukoliko je dobio prethodnu saglasnost Kupca. S toga će Kupca svoju saglasnost dati u najkraćem mogućem roku od momenta prijema odgovora Prodavca na reklamaciju, kako bi Prodavac mogao da reši reklamaciju u gore spomenutom zakonskom roku. Neblagovremeno davanje saglasnoti Kupca smatraće se jednim od objektivnimh razloga zbog kojih Prodavac nije u mogućnosti da udovolji zahtevu Kupca u zakonskom roku.</p>
        <br><p>Ukoliko prodavac iz objektivnih razloga nije u mogućnosti da udovolji zahtevu Kupca u roku koji je dogovoren, dužan je da o produžavanju roka za rešavanje reklamacije obavesti Kupca i navede rok u kome će je rešiti, kao i da dobije njegovu saglasnost, koju će Kupac dati u najkraćem mogućem roku. Produžavanje roka za rešavanje reklamacija moguće je samo jednom.</p>
        <br><p>Prodavac se obavezuje da će svaki proizvod koji je predat na servis a čija reklamacija nije rešena u dogovorenom roku zameniti novim, istim ili odgovarajućim artiklom.Ukoliko Kupac ne prihvati zamenu artikla za drugi odgovarajući, Kupcu će biti vraćen iznos kupoprodajne cene.</p>
        <br><p>Kupac je dužan da popravljeni proizvod preuzme najkasnije u roku od 30 dana od trenutka kada je dobio obaveštenje da može preuzeti proizvod sa servisa. Nakon isteka tog perioda Prodavac ne preuzima više nikakvu odgovornost za dati proizvod i proizvod može biti predat na recikliranje.</p>
        <br><p>Član 6.</p>
        <br><p>Ukoliko se proizvodi kupuju na daljinu (npr. preko internet sajta Prodavca) i isporučuju na adresu kupca, kupac ima pravo da da odustane od ugovora zaključenog na daljinu, u roku od 14 dana, bez navođenja razloga i dodatnih troškova, osim troškova vraćanja robe, koje u ovom slučaju snosi Kupac. Kod ugovora o prodaji robe, rok od 14 dana računa se od trenutka kada roba dospe u državinu Kupca, odnosno trećeg lica koje je odredio Kupac, a koje nije prevoznik.Kada Kupac jednom porudžbenicom naruči više vrsta roba koje se isporučuju zasebno, rok od 14 dana počinje da teče kada poslednja vrsta naručene robe dospe u državinu Kupca, odnosno trećeg lica koje je odredio Kupac, a koje nije prevoznik.Kada se isporuka robe sastoji iz više pošiljki i delova, rok od 14 dana počinje da teče kada je poslednja pošiljka ili deo, dospeo u državinu Kupca, odnosno trećeg lica koje je odredio Kupac, a koje nije prevoznik. Rok iz ovog stava ističe protekom poslednjeg časa poslednjeg dana roka.</p>
        <br><p>Kupac ostvaruje pravo na odustanak od ugovora izjavom koju može dati na posebnom obrascu za odustanak od ugovora zaključenog na daljinu, odnosno izvan poslovnih prostorija ili na drugi nedvosmislen način (u daljem tekstu: obrazac za odustanak).Izjava o odustanku od ugovora kod ugovora na daljinu i ugovora koji se zaključuju izvan poslovnih prostorija smatra se blagovremenom ukoliko je poslata Prodavcu u roku iz stava 1. ovog člana. Izjava o odustanku od ugovora proizvodi pravno dejstvo od dana kada je poslata Prodavcu. Ako Prodavac omogući Kupcu da elektronski popuni i pošalje obrazac za odustanak, dužan je da ga o prijemu obrasca bez odlaganja obavesti u pisanoj formi ili na drugom trajnom nosaču zapisa.</p>
        <br><p>Prodavac će u trenutku zaključenja ugovora, a najkasnije prilikom isporuke robe predati Kupcu u pisanoj formi ili na trajnom noaču zapisa obrazac za odustanak i primerak potpisanog ugovora. Obaveštenje Kupcu iz člana 27. st. 1. i 2. Zakona o zaštiti potrošača (adresi poslovanja Prodavca, adresi, broju faksa i adresi elektronske pošte Prodavca na koju Kupac može da izjavi reklamaciju i ceni robe) nalazi se u tekstu ovog ugovora.</p>
        <br><p>Početkom roka iz stava 1 ovog člana, prestaje pravo Kupca na odustanak od ugovora.</p>
        <br><p>Prodavac je u slučaju zakonitog odustanka od ugovora dužan da Kupcu bez odlaganja vrati iznos koji je Kupac platio po osnovu ugovora, a najkasnije u roku od 14 dana od dana kada je primio obrazac za odustanak. Prodavac može da odloži povraćaj sredstava dok ne dobije robu koja se vraća, ili dok Kupac ne dostavi dokaz da je poslao robu Prodavcu u zavisnosti od toga šta nastupa prvo. Kupac je dužan da vrati robu Prodavcu ili licu ovlašćenom od strane Prodavca, bez odlaganja, a najkasnije u roku od 14 dana od dana kada je poslao obrazac za odustanak. Kupac snosi isključivo direktne troškove vraćanja robe. Kupac je isključivo odgovoran za umanjenu vrednost robe koja nastane kao posledica rukovanja robom na način koji nije adekvatan, odnosno prevazilazi ono što je neophodno da bi se ustanovili priroda, karakteristike i funkcionalnost robe. Kupać će proizvod vratiti u neoštećenoj originalnoj ambalaži, sa svom pripadajućom dokumentacijom koja se nalazi u originalnom pakovanju i u istom stanju u kakvom je i isporučen, bez ikakvih mehaničkih ili bilo kakvih drugih oštećenja.</p>
        <br><p>Kupac nema pravo da odustane od ugovora u slučaju:</p>
        <br><p>Isporuke robe ili pružanja usluga čija cena zavisi od promena na finansijskom tržištu na koje Prodavac ne može da utiče i koje mogu nastati u toku roka za odustanak<br />
        Isporuke robe proizvedene prema posebnim zahtevima Kupca ili jasno personalizovane<br />
        Isporuke zapečaćene robe, zapečaćenih audio, video zapisa ili računarskog softvera, koji su otpečaćeni nakon isporuke<br />
        Isporuke robe koja se, nakon isporuke, zbog svoje prirode neodvojivo meša sa drugom robom<br />
        isporuke digitalnog sadržaja koji nije isporučen na trajnom nosaču zapisa ako je izvršenje započelo posle prethodne izričite saglasnosti Kupca i njegove potvrde da zna da na taj način gubi pravo na odustanak od ugovora<br />
        Ovim Ugovorom Kupac daje izričitu saglasnost isporuke digitalnog sadržaja koji nije isporučen na trajnom nosaču zapisa i potvrđuje da zna da na taj način gubi pravo na odustanak od ugovora.</p>
        <br><p>Član 7.</p>
        <br><p>Saobraznost se daje isključivo na ispravnost uređaja a ne na njegovu funkcionalnost jer se podrazumeva da je Kupac upoznat sa tehničkim karakteristikama proizvoda, pa se saobraznost odnosi na činjenicu da će izabrani proizvod zadovoljiti zahteve kupca u okviru deklarisanih tehničkih mogućnosti propisanih od strane proizvođača. Saobraznost se ne odnosi na poslove održavanja proizvoda tj. čišćenje i sl. Od Kupca se očekuje da kupljeni proizvod ne izlaže štetnim dejstvima (duvanski dim, ekstremno prašnjave prostorije, ekstremno hladne ili ekstremno tople prostorije i sl.). Sve eventualne nepravilnosti prouzrokovane ovakvim tretmanom robe će se otklanjati isključivo na teret Kupca po važećem ćenovniku servisnih usluga.</p>
        <br><p>Pravo na saobraznost nije moguće ostvariti ukoliko je do oštećenja ili kvara robe došlo usled transporta nakon isporuke, usled nepravilne montaže, usled nepravilnog održavanja, usled neispravnih električnih instalacija, nestabilnog napona ili usled strujnog udara ili udara groma, usled više sile (poplava, zemljotres, požar i sl.), usled nepravilnog korišćenja, usled nepridržavanja proizvođačkog uputstva i preporuka o upotrebi proizvoda, usled korišćenja neodgovarajućeg potrošnog materijala koji nije kupljen uz proizvod, usled bilo kakvog mehaničkog oštećenja proizvoda koje je nastalo krivicom Kupca ili trećeg lica za koje Prodavac ne odgovara, usled neovlašćenog popravljanja proizvoda od strane trećeg lica koje nije ovlašćeno od Prodavca ili proizvođača, ukoliko je proizvod vraćen bez fiskalnog računa ili drugog dokaza da je kupljen kod Prodavca.</p>
        <br><p>Kupac je dužan da prilikom preuzimanja kupljenog proizvoda ustanovi kompletnost i fizičku neoštećenost proizvoda koje preuzima. Naknadne reklamacije koje se odnose na kompletnost i fizičku neoštećenost neće biti prihvaćene.</p>
        <br><p>Kupac će sačuvati originalnu ambalažu kupljenog prizvoda i koristiti je pri svakom internom i eksternom transportu.</p>
        <br><p>Pre nego što se obrati za tehničku pomoć, Kupac će proveriti da li su obezbeđeni svi neophodni uslovi za nesmetanu upotrebu kupljenog proizvoda.</p>
        <br><p>Kupac potvrđuje da mu je prilikom potpisivanja ovog ugovora predata izjava o saobraznosti za robu.</p>
    </div>
</section>