name: Build and Send Email with SendGrid

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET 8
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Run the application with SendGrid
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SENDGRID_FROM: ${{ secrets.SENDGRID_FROM }}
        run: dotnet run --project path-to-your-project
